apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo-container
        image: docker-image:tag 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
