# -*- coding: utf-8 -*-
"""model_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JGqNUnjRhPwd0v9liSxWOtEnnEr3kBX0
"""

import cv2
import numpy as np

def load_yolo_model(model_path):

    model = cv2.dnn.readNetFromTensorflow('gs://my-mksp-bucket/object-detection-model.pb')
    pass

def perform_inference(model, image):
    detections = model.detect('gs://my-mksp-bucket/object-detection-model.pb')
    pass

if __name__ == "__main__":
    yolo_model_path = 'gs://my-mksp-bucket/object-detection-model.pb'

    # Load YOLO model
    yolo_model = load_yolo_model(yolo_model_path)

    video_path = 'gs://my-mksp-bucket/vid10.mp4'
    cap = cv2.VideoCapture(video_path)

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Perform inference on the current frame
        detections = perform_inference(yolo_model, frame)

        # Display the result or save it to an output video
        cv2.imshow('YOLO Inference', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()